enum_discrim_align_threshold = 60
format_macro_matchers = true
hard_tabs = true
imports_granularity = "Crate"
max_width = 120
overflow_delimited_expr = true
reorder_impl_items = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
